export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"
export const APP_LOAD = "APP_LOAD"
export const REDIRECT = "REDIRECT"
export const ASYNC_START = "ASYNC_START"
export const CLEAR_ERROR = "CLEAR_ERROR"